- src/index.html
I inserted a comment to test my change
> test change

- index.html
> Amos branch

- index.html
> recent comment

- .gitignore
- src/classmentors/components/classmentors/classmentors-view.html
- src/classmentors/components/cohort/cohort-view.html
- src/classmentors/components/cohort/cohort.js
- src/classmentors/components/index.js
- src/classmentors/services/routes.js
updated routes, components and routeconfigs, added cohort-view.html
> close #38 

- .gitignore
- src/classmentors/components/challenges/mcq/mcq-view-mcq.html
- src/classmentors/components/events/events-view-event-task-form.html
- src/classmentors/components/events/events.js
For new challenge creation. UX considerations.
> Added dialog box to cancel button   #23 

- src/classmentors/components/events/events-view-event-table-participants.html
- src/classmentors/components/events/events-view-provide-code.html
- src/classmentors/components/events/events-view-provide-link.html
- src/classmentors/components/events/events-view-provide-response.html
- src/classmentors/components/events/events.js
Finalised code challenge functionality. 
Also, fixed bug of response to challenge "save" button only activating when enter is pressed. Now activates on click as well.
> #62 refining the code challenge

- security_rules/security-rules.json
- src/classmentors/components/events/events-view-event-table-results.html
- src/classmentors/components/events/events-view-event-task-form.html
- src/classmentors/components/events/events-view-event.html
- src/classmentors/components/events/events-view-provide-link.html
- src/classmentors/components/events/events-view-provide-response.html
- src/classmentors/components/events/events.css
- src/classmentors/components/events/events.js
- src/classmentors/services.js
- Enabled result support for link challenges.
- Also implemented a link preview when reviewing link submissions
- Implemented scoring of tasks by participant in the results tab (scoring can be reused for MCQ and other graded functionality
- Implemented sorting by scores in the result tab
> #72 & misc enhancements

- security_rules/security-rules.json
- src/classmentors/components/classmentors/classmentors-view.html
- src/classmentors/components/cohort/cohort-view.html
- src/classmentors/components/cohorts/cohorts-edit-cohort.html
- src/classmentors/components/cohorts/cohorts-new-cohort.html
- src/classmentors/components/cohorts/cohorts-view-cohort.html
- src/classmentors/components/cohorts/cohorts-view.html
- src/classmentors/components/cohorts/cohorts.css
- src/classmentors/components/cohorts/cohorts.js
- src/classmentors/components/cohorts/cohorts.specs.js
- src/classmentors/components/events/events-view-event-task-form.html
- src/classmentors/components/events/events-view-event.html
- src/classmentors/components/events/events-view-password.html
- src/classmentors/components/events/events-view-provide-link.html
- src/classmentors/components/events/events.js
- src/classmentors/index.js
- src/classmentors/index.specs.js
- src/classmentors/services.js
- Implemented cohorts UI.
- Enabled creation of cohorts by selecting events to aggregate.
- Selection and filtration of cohorts by featured, joined, created in a tabbed layout similar to that in events.
- Implemented access control to joined cohorts according to whether the user has joined any of the events under a particular cohort.
- Implemented navigation to individual cohorts.
- Implemented tabbed UI within a cohort for announcements, ranking, and stats.
- Implemented editing of a cohort. Currently only supports changing cohort name and creating announcements.
- Implemented basic view on announcements tab to view created announcements for a particular cohort.
> Cohorts #73,74

- security_rules/security-rules.json
- src/classmentors/components/classmentors/classmentors-view.html
- src/classmentors/components/cohorts/cohorts-edit-cohort.html
- src/classmentors/components/cohorts/cohorts-new-cohort.html
- src/classmentors/components/cohorts/cohorts-view-cohort-stats-page.html
- src/classmentors/components/cohorts/cohorts-view-cohort.html
- src/classmentors/components/cohorts/cohorts.css
- src/classmentors/components/cohorts/cohorts.js
- src/classmentors/components/events/events-view-event-table-results.html
- src/classmentors/components/events/events-view-provide-code.html
- src/classmentors/components/events/events.js
- src/classmentors/filters.js
- src/classmentors/index.js
- src/classmentors/module.js
- src/classmentors/services.js
- src/jspm.config.js
- tools/assets/index.html
Implemented cohort announcements and editing and misc cohort maintenance details. Miscellaneous bug fixes as well
> Cohorts #79 #82

- src/classmentors/components/challenges/challenges.js
- src/classmentors/components/challenges/mcq/mcq-view-mcq-edit.html
- src/classmentors/components/challenges/mcq/mcq-view-mcq.html
- src/classmentors/components/challenges/mcq/mcq-view-start.html
- src/classmentors/components/challenges/mcq/mcq.js
- src/classmentors/components/events/events-view-event-task-form.html
- src/classmentors/components/events/events.js
- src/classmentors/index.js
- src/classmentors/services.js
#	src/classmentors/components/events/events.js
^resolve conflicts?
> close Issue #23

- security_rules/package.json
- src/classmentors/components/challenges/survey/survey-view-survey.html
- src/classmentors/components/events/events-view-eduDisLearn-task-form.html
- src/classmentors/components/events/events-view-motiStratLearn-task-form.html
- src/classmentors/components/events/events-view-schEngageScale-task-form.html
- src/classmentors/components/events/events.js
- src/classmentors/services.js
close #90 Save all responses upon submit, redirects users back to challenge page.
> 90 survey saveall submit

- src/classmentors/components/challenges/mcq/mcq-view-start.html
- src/classmentors/components/challenges/mcq/mcq.js
- src/classmentors/components/events/events-view-event-task-form.html
-Resolved merge conflicts
-Answer options are either radio buttons or checkboxes depending on number of answers
> close Issue #105

- src/classmentors/components/challenges/survey/survey-view-survey.html
- src/classmentors/components/events/events-view-eduDisLearn-task-form.html
- src/classmentors/components/events/events-view-event-table-participants.html
- src/classmentors/components/events/events.js
- src/classmentors/services.js
close #120 saved all responses when user clicks submit, then redirects user back to events pages. Done for all 3 surveys.
> 120 saveall for edu dissatisfaction survey

- src/classmentors/components/challenges/mcq/mcq.js
show notification when user finishes the mcq
> #116 added notification

- src/classmentors/components/events/events-view-eduDisLearn-task-form.html
- src/classmentors/components/events/events-view-motiStratLearn-task-form.html
- src/classmentors/components/events/events-view-schEngageScale-task-form.html
- src/classmentors/components/events/events.js
close #141  added discard button to redirect user back to challenges page, remove save button to disallow students from saving individual response, redesign table styles to have striped layout.
> 141 divider and savebuttonenhancement

- src/classmentors/components/events/events-view-eduDisLearn-task-form.html
- src/classmentors/components/events/events-view-motiStratLearn-task-form.html
- src/classmentors/components/events/events-view-schEngageScale-task-form.html
- src/classmentors/components/events/events.js
- src/jspm.config.js
closes #164 disable submit button when user has not completed the survey. only
enable it once he has completed them
> #164 disable submit button

- src/classmentors/components/events/events.js
#170 user can submit survey responses of all 3 templates in a new event
> #170 user can submit survey response in a new event

- src/classmentors/components/challenges/mcq/mcq-view-start.html
- src/classmentors/components/challenges/mcq/mcq.js
- ng-requred fixed for both checkbox and radio button
- submit button fixed
> close #162

- src/classmentors/components/events/events-view-event-task-form.html
close #191 removed index card challenge and align radiobuttons properly
> #191 removed index card challenge

- package.json
- src/classmentors/components/events/events-view-event-table-participants.html
close #197 students are able to see view team activity on challenge page
> 197 view team challenge

- src/classmentors/components/events/events-view-event-table-participants.html
- src/classmentors/components/events/events.js
- src/classmentors/services.js
close #193 debugged progress tracking. Progress in survey will not bounce back
to 0% after user participates in a link challenge. Also changed "Survey
Completed" to "Completed" for consistency.
> #193-debugged-progress-tracking

- src/classmentors/components/challenges/challenges.js
- src/classmentors/components/challenges/teamActivity/teamactivity-view-irat-start.html
- src/classmentors/components/challenges/teamActivity/teamactivity.js
- src/classmentors/components/events/events-view-event-table-participants.html
- src/classmentors/components/events/events-view-teamFormation.html
- src/classmentors/components/events/events.js
- src/classmentors/index.js
- src/classmentors/services.js
close #189 UI for student view for attempting IRAT
close #178 UI for student to form and join team
> Student attemp IRAT and Team Formation

- src/classmentors/components/events/events.js
close #129 Changed wrong password error message from permission denied to invalid
password.
> Changed password invalid message.

- src/classmentors/components/challenges/mcq/mcq.js
- src/classmentors/components/events/events-view-event-task-form.html
- src/classmentors/services.js
- fixed progress bug for mcq
- UI fix for task creation page 
- profile edit > profile update in task creation pg
- commented sensitive console.log.
> close #208 progress bug

- src/classmentors/components/challenges/challenges.js
- src/classmentors/components/challenges/teamActivity/team-view-create.html
- src/classmentors/components/challenges/teamActivity/teamactivity.js
- src/classmentors/components/events/events.js
-revamped layout
- missing assistance text to show how many teams/ number of students per team.
> close #172 

- src/classmentors/components/challenges/challenges.js
- src/classmentors/components/challenges/teamActivity/teamactivity-view-irat-start.html
- src/classmentors/components/challenges/teamActivity/teamactivity-view-trat-start.html
- src/classmentors/components/challenges/teamActivity/teamactivity.js
- src/classmentors/components/events/events-view-event-table-participants.html
- src/classmentors/index.js
close #190 created UI for TRAT for student view
> #190 UI for TRAT

- src/classmentors/components/challenges/teamActivity/team-view-create.html
- src/classmentors/components/challenges/teamActivity/teamactivity.js
showing assistance text when creating team to let user know how many
teams will be created or th maximum enrollment for a team given the
setting.
> close #215 showing assistance text

- package.json
- src/classmentors/components/challenges/teamActivity/teamactivity.js
- src/classmentors/components/events/events.js
- src/classmentors/index.js
- src/jspm.config.js
close #157 warn users if he navigates away while doing the survey
> 157 warn users

- src/classmentors/components/challenges/challenges.js
- src/classmentors/components/challenges/teamActivity/teamActivity.css
- src/classmentors/components/challenges/teamActivity/teamactivity-view-trat-start.html
- src/classmentors/components/challenges/teamActivity/teamactivity.js
- src/classmentors/filters.js
- src/classmentors/index.js
implemented irat, team formation and trat functionalities
> Issue #179

- src/classmentors/components/challenges/mcq/mcq-view-mcq.html
- src/classmentors/components/challenges/mcq/mcq.js
- src/classmentors/components/challenges/teamActivity/teamactivity-view-teamFormation.html
- src/classmentors/components/challenges/teamActivity/teamactivity.js
- src/classmentors/components/events/events-view-event-edit.html
- src/classmentors/components/events/events-view-event-task-form.html
- src/classmentors/components/events/events-view-list.html
- src/classmentors/components/events/events-view-new.html
- src/classmentors/components/events/events.css
- src/classmentors/components/events/events.js
- src/classmentors/services.js
close #247 allow users to feature events, collapsable and expandable button, disable teamformation radiobutton once user is full
> 247 usability enhancement

- src/classmentors/components/events/events-view-event-table-participants.html
- src/classmentors/components/events/events.js
close#259 close#256 Show change team button instead of form team after user has selected a team to join. Disable the team that the user can join if the team reaches max size
> Debugged team formation

- src/classmentors/components/challenges/challenges.js
- src/classmentors/components/events/events.js
[bugfix] Display full name for team leaders
> [bugfix] close #258

- src/classmentors/components/events/events-view-event-table-participants.html
- src/classmentors/components/events/events.js
to fix bug in previous bug fix
> close #258

- src/classmentors/components/challenges/teamActivity/teamactivity-view-teamFormation.html
- src/classmentors/components/events/events.js
close#264 Change public id to display name in team formation
> Team formation change public Id to display name

- database/security-rules.json
- src/classmentors/components/classmentors/classmentors-view.html
- src/classmentors/components/feedback/feedback.html
- src/classmentors/components/feedback/feedback.js
- src/classmentors/components/index.js
- src/classmentors/index.js
- src/classmentors/services.js
Enabled submission of qualitative and quantitative feedback
> User feedback

- package.json
- src/classmentors/components/challenges/mcq/mcq-view-mcq-edit.html
- src/classmentors/components/challenges/mcq/mcq-view-mcq.html
- src/classmentors/components/challenges/mcq/mcq-view-start.html
- src/classmentors/components/challenges/survey/survey-view-survey.html
- src/classmentors/components/challenges/teamActivity/team-view-create.html
- src/classmentors/components/challenges/teamActivity/teamactivity.js
- src/classmentors/components/events/events-view-eduDisLearn-task-form.html
- src/classmentors/components/events/events-view-event-task-form.html
- src/classmentors/components/events/events-view-motiStratLearn-task-form.html
- src/classmentors/components/events/events-view-new.html
- src/classmentors/components/events/events-view-provide-link.html
- src/classmentors/components/events/events-view-provide-response.html
- src/classmentors/components/events/events-view-schEngageScale-task-form.html
- src/classmentors/components/events/events.js
- src/classmentors/components/profiles/profiles-view-edit.html
-standardization of button UI (back & submit)
- changed navigation bar "leave" to "leave event"
> close #285 , close #280 , close #282 

- src/classmentors/components/classmentors/classmentors-view.html
- src/classmentors/components/events/events-view-event-task-form.html
- src/classmentors/components/events/events.js
- src/classmentors/components/feedback/feedback.js
- src/classmentors/components/index.js
- src/classmentors/components/question-queue/question-queue.html
- src/classmentors/components/question-queue/question-queue.js
- src/classmentors/index.js
QQ base controller (Non-navigable in UI until function is complete)
Fixed editing of profile edit challenges
Converted all question input areas to textarea instead of text input
> Question queue

- src/classmentors/components/challenges/challenges.js
- src/classmentors/components/challenges/mcq/mcq.js
- src/classmentors/components/challenges/survey/survey-view-survey.html
- src/classmentors/index.js
-fixed survey editing 
- UI changes to survey creation/editing
> close #279 

- src/classmentors/components/classmentors/classmentors-view.html
- src/classmentors/components/classmentors/classmentors.js
close #283 navigation button at nav bar will be highlighted showing where user is at.
> 283 focusbuttons

- src/classmentors/components/events/events.js
- src/classmentors/services.js
close #300 update progress once user has formed team
> Update progress on teamformation

- src/classmentors/components/challenges/teamActivity/team-view-create.html
close #286 Users cannot proceed unless he fills up the required input in the form.
The create button will be disabled until all required fields are filled.
> Debug TeamFormation task creation

- src/classmentors/components/challenges/challenges.js
- src/classmentors/components/challenges/mcq/mcq.js
- src/classmentors/components/events/events-view-event-task-form.html
- src/classmentors/components/events/events-view-provide-link.html
- src/classmentors/components/events/events.js
-fixed usability issue with link pattern challenge
- allow help link to accomodate links starting with www.
- when attempting mcq, nav bar shows correct path with this pull.
> close #287 , close #201 , close #303 

- src/classmentors/components/challenges/teamActivity/teamactivity.js
- src/classmentors/components/events/events.js
close #299 included question number inside eventlog
> 299 debugtrat

- src/classmentors/index.js
Added routeProtection which prevents users from clicking back after completing an activity. Must place protected route in index.js
> close #310

- src/classmentors/components/challenges/challenges.js
- src/classmentors/components/challenges/teamActivity/teamactivity.js
- src/classmentors/components/events/events-view-event-table-participants.html
- src/classmentors/components/events/events.js
- src/classmentors/services.js
close #309 different team leaders can now be shown in different challenges
> 309 debugtrat

- src/classmentors/components/challenges/teamActivity/teamactivity-view-teamFormation.html
- src/classmentors/components/challenges/teamActivity/teamactivity.js
- src/classmentors/components/events/events.js
close #306 Allow users to leave team once they have joined
> Leave Team Function

- src/classmentors/components/challenges/teamActivity/teamactivity.js
- src/classmentors/components/events/events-view-event-table-participants.html
Fixed ‘your team leader is:’ message. That was previously displaying incorrectly
> close #317

- src/classmentors/components/challenges/challenges.js
- src/classmentors/components/challenges/mentoring/mentor-create-view.html
- src/classmentors/components/challenges/mentoring/mentoring.js
- src/classmentors/components/events/events-view-event-task-form.html
- src/classmentors/components/events/events.js
- src/classmentors/index.js
close #328 created controller function for mentoring challenge
> Created Mentor Controller

- src/classmentors/components/events/events-view-event-table-participants.html
- src/classmentors/components/events/events.js
close #331 users will not see submit response in the submit code challenge
> debug submit code

- src/classmentors/components/challenges/teamActivity/teamactivity.js
- src/classmentors/components/events/events-view-event-table-participants.html
- src/classmentors/components/events/events-view-provide-voteQuestion.html
- src/classmentors/components/events/events.js
unable to fix display bug for vote questions. Will attempt to fix it in another PR
> close #327

- src/classmentors/components/challenges/teamActivity/team-view-create.html
close #337 prevent admin from creating teams lesser than 0
> Prevent team formation going below 0

- src/classmentors/components/challenges/challenges.js
- src/classmentors/components/challenges/mcq/mcq.js
- src/classmentors/components/challenges/teamActivity/teamactivity-view-teamFormation.html
- src/classmentors/components/challenges/teamActivity/teamactivity.js
- src/classmentors/components/events/events-view-event-task-form.html
- src/classmentors/components/events/events-view-provide-reviewQuestion.html
- src/classmentors/components/events/events-view-provide-voteQuestion.html
- src/classmentors/components/events/events.js
- Fixed spfNavBarService for MCQ, Survey and Team activity
- corrected cosmetic bugs
> close #341, close #340, close #329, close #342 

- database/security-rules.json
- src/classmentors/components/challenges/teamActivity/team-view-create.html
- src/classmentors/components/challenges/teamActivity/teamactivity.js
- src/classmentors/components/events/events-view-event-table-participants.html
- src/classmentors/components/events/events.js
- src/classmentors/services.js
close #345 created Cooperative Submission Challenge :+1:
> 345 cooplearning

- src/classmentors/components/events/events-view-event-table-participants.html
- src/classmentors/components/events/events.js
change display name for teamleader and coop edit close #354  close #353
> change display name for teamleader and coop edit

- src/classmentors/components/events/events-view-event.html
- src/classmentors/components/events/events-view-list.html
changed landing tabs to featured event, and on the challenge tab.
> close #357

- src/classmentors/components/challenges/challenges.js
- src/classmentors/components/challenges/survey/edudiss-view-preview.html
- src/classmentors/components/challenges/survey/motistrat-view-preview.html
- src/classmentors/components/challenges/survey/schengage-view-preview.html
- src/classmentors/components/challenges/survey/survey-view-survey.html
- src/classmentors/components/challenges/survey/survey.js
- src/classmentors/components/events/events-view-eduDisLearn-task-form.html
- src/classmentors/components/events/events-view-schEngageScale-task-form.html
- src/classmentors/components/events/events.js
- src/classmentors/index.js
close #323 allow users to see preview of the surveys when creating the templates.
> 323 previewsurvey

- src/classmentors/components/challenges/mcq/mcq.js
- src/classmentors/components/challenges/teamActivity/teamactivity-view-teamFormation.html
- src/classmentors/components/challenges/teamActivity/teamactivity.js
- src/classmentors/components/events/events-view-event-table-participants.html
- src/classmentors/components/events/events.js
- src/classmentors/services.js
> 363 jointeamenhancement

- src/classmentors/components/events/events.js
> debug teamformation

- src/classmentors/components/events/events-view-event-table-results.html
- src/classmentors/components/events/events-view-provide-link.html
- link submission in results tabs will open in new window instead.
> close #336 

- src/classmentors/components/events/events-view-edit-profile.html
- src/classmentors/components/events/events-view-event-table-participants.html
- changed button text in participant table
- changed the feel and look for profile challenge for students.
> close #359, close #281

- src/classmentors/components/challenges/teamActivity/teamactivity.js
-fixed spfNavBarService for TRAT
> close #364 

- src/classmentors/components/challenges/survey/survey-view-survey.html
- src/classmentors/components/question-queue/event-queue.html
- src/classmentors/components/question-queue/question-queue.html
- src/classmentors/components/question-queue/question-queue.js
- src/classmentors/components/question-queue/view-question.html
- changed list of question forums to cards
-removed show more/show less 
- added spfAlert when open/close forum
- other cosmetic changes
> close #374 

- src/classmentors/components/cohorts/cohorts-edit-cohort.html
- src/classmentors/components/cohorts/cohorts-view-cohort.html
- src/classmentors/components/cohorts/cohorts.js
- src/packages/singpath-core/src/config.js
- changed main website color to indigo
- UI improvements to cohorts
> close #325 

- src/classmentors/components/challenges/teamActivity/teamActivity.css
- src/classmentors/components/challenges/teamActivity/teamactivity.js
- src/classmentors/components/events/events-view-event-edit.html
- src/classmentors/components/events/events.css
- src/classmentors/components/events/events.js
- cosmetic changes to event challenges (added collapsible)
> close #378 

- src/classmentors/components/challenges/survey/survey-view-survey.html
- src/classmentors/components/challenges/teamActivity/team-view-create.html
- src/classmentors/components/challenges/teamActivity/teamActivity.css
- src/classmentors/components/challenges/teamActivity/teamactivity-view-trat-start.html
- src/classmentors/components/challenges/teamActivity/teamactivity.js
- src/classmentors/components/events/events-view-event-edit.html
- src/classmentors/components/events/events.js
-ability to post question on question queue for team questions removed
- warn users that he cannot edit team activities upon creation
-cosmetic changes to team activities page.
-remove Ability to set time limit for quiz
-other cosmetic changes
> close #347 , close #376 ,close #350 , close #119

- src/classmentors/components/events/events-view-event-table-participants.html
- src/classmentors/components/events/events-view-provide-code.html
- src/classmentors/components/events/events.js
-fixed update profile button on event table
- disabled save button when viewing other parti's codes
> close #344
